experiment:
  id: "vibraclip_experiment_id"

paths:
  root_dir: "<<YOUR_PATH>>/vibraclip"
  db_path: "/data/qm9s_ir_raman.lmdb"
  checkpoint_path: "/checkpoints"
  pre_trained_path: "/pre_trained"

logging:
  wandb_project: "vibraclip"
  offline: False

dataset:
  val_ratio: 0.1
  test_ratio: 0.1
  batch_size: 128
  num_workers: 0
  transform: True

training:
  max_epochs: 200
  head_lr: 0.0004
  gnn_encoder_lr: 0.0004
  spectra_lr: 0.0004
  weight_decay: 0.1
  lr_scheduler_patience: 5
  lr_scheduler_factor: 0.1
  temperature: 141
  molecular_mass: True
  loss_allpairs: True

model:
  g_encoder:
    hidden_channels: 128
    out_channels: 181
    num_blocks: 4
    int_emb_size: 64
    basis_emb_size: 8
    out_emb_channels: 256
    num_spherical: 7
    num_radial: 6
    cutoff: 5.0
    max_num_neighbors: 32
    envelope_exponent: 5
    num_before_skip: 1
    num_after_skip: 2
    num_output_layers: 3
  spectra_encoder:
    input_dim: 1750
    hidden_dim: 1262
    n_layers: 1
    out_features: 497
    act_fun: "elu"
    batch_norm: True
  projection:
    latent_dim: 861
    layer_norm: True
    dropout: False
    p_dropout: 0.0
    bias: False
